---
version: "3.8"

networks:
  main-cidr:
    name: main-cidr
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${CIDR}
          gateway: ${GW}

volumes:
  rootmedia:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER},nfsvers=4"
      device: ":${NFS_SERVER_DATA_PATH}"
  media:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER},nfsvers=4"
      device: ":${NFS_SERVER_DATA_PATH}/media"
  torrents:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER},nfsvers=4"
      device: ":${NFS_SERVER_DATA_PATH}/torrents"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=claim--z84hm5ZjjKzN1wtbS6U
    volumes:
      - ./container-configs/plex:/config
      - media:/mnt/media
    devices:
      - /dev/dri/:/dev/dri/
    restart: always

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    networks:
      - main-cidr
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888 # HTTP proxy
      - 8085:8085 # qbittorrent
    volumes:
      - ./container-configs/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - SERVER_CITIES=${SERVER_CITIES}
      - TZ=${TZ}
      - UPDATER_PERIOD=24h
    restart: always
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8085
    volumes:
      - ./container-configs/qbittorrent:/config
      - torrents:/mnt/torrents
    depends_on:
      - gluetun
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - main-cidr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./container-configs/prowlarr:/config
      - rootmedia:/mnt
    ports:
      - 9696:9696
    restart: always
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - main-cidr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./container-configs/radarr:/config
      - rootmedia:/mnt
    ports:
      - 7878:7878
    restart: always
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - main-cidr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./container-configs/sonarr:/config
      - rootmedia:/mnt
    ports:
      - 8989:8989
    restart: always

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    networks:
      - main-cidr
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./container-configs/npm:/data
      - ./container-configs/letsencrypt:/etc/letsencrypt
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    networks:
      - main-cidr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./container-configs/heimdall:/config
    ports:
      - 8080:80
    restart: always

  # dnsutils:
  #   image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
  #   container_name: dnsutils
  #   restart: unless-stopped